### ISSUE TITLE
AttributeError: 'TmodbusUnit' object has no attribute 'require_timeout' — incompatible with HA 2026.9 tmodbus backend

### ISSUE THREAD

**Issue by stefanhintermayr** [andreasreinhardt81/varta_modbus_hacs#2]
Labels: bug

Describe the bug

Since Home Assistant 2026.9, the modbus_connection integration uses tmodbus as its backend instead of pymodbus. varta_modbus v1.1.2 calls unit.require_timeout(), unit.require_message_spacing() and unit.require_connect_delay() on the ModbusUnit object — methods that exist only in the pymodbus backend but not in TmodbusUnit. The integration therefore fails at setup with "Unknown error occurred".

To Reproduce

Install varta_modbus v1.1.2 via HACS
Restart Home Assistant 2026.9.x
Go to Settings → Devices & Services → Add Integration → VARTA Modbus
Enter Host, Port 502, Unit ID → click OK
"Unknown error occurred" is shown

Expected behavior

Integration sets up successfully.

Error in logs

File "/config/custom_components/varta_modbus/config_flow.py", line 40, in async_validate_input
    device = VartaStorage(unit)
  File "/config/custom_components/varta_modbus/vendor/varta_modbus/device.py", line 43, in __init__
    unit.require_timeout(3.0)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TmodbusUnit' object has no attribute 'require_timeout'

Environment

Home Assistant version: core-2026.9.3
Installation type: Home Assistant OS
varta_modbus version: 1.1.2
modbus-connection version: 4.12.1 (installed via pip, not auto-installed by HA)
Python: 3.14.6

Additional context

Note: modbus-connection was not automatically installed by HA despite being listed in manifest.json as "requirements": ["modbus-connection>=4.12.1"]. Manual pip3 install "modbus-connection>=4.12.1" was required. This may be a secondary bug worth investigating separately.

The root cause is that vendor/varta_modbus/device.py calls optional capability methods (require_timeout, require_message_spacing, require_connect_delay) without checking whether they exist on the unit object first — though the real fix is ensuring compatibility with the tmodbus backend that HA 2026.9 provides.

Possible fix

Either:

Check hasattr(unit, 'require_timeout') before calling (short-term workaround), or
Ensure the vendored varta_modbus library is tested and compatible with the tmodbus backend

**Comment by stefanhintermayr** [comment]
<html>
<body>
<p dir="ltr"><strong>Workaround / Affected versions</strong></p>
<p dir="ltr">Version <strong>1.1.1</strong> works correctly with HA 2026.9. It uses <code>getattr(unit, "require_timeout", None)</code> to safely check for the method before calling it, which makes it compatible with both the pymodbus and tmodbus backends.</p>
<p dir="ltr">Version <strong>1.1.2</strong> regressed this fix by calling <code>unit.require_timeout(3.0)</code> directly, without the <code>getattr</code> guard — causing the <code>AttributeError</code> on tmodbus.</p>
<p dir="ltr"><strong>Suggested fix for 1.1.2</strong></p>
<p dir="ltr">Restore the <code>getattr</code> pattern from 1.1.1:</p>
<div><div role="group" aria-label="python-Code" tabindex="0"><div><div></div></div><div>python</div><div><pre style="color: rgb(20, 24, 31); background: transparent; font-family: var(--font-mono);"><code class="language-python" style="color: rgb(20, 24, 31); background: transparent; font-family: var(--font-mono); white-space: pre;"><span><span><span style="color: rgb(110, 118, 135);"># Instead of:</span>
</span><span>unit<span style="color: rgb(43, 48, 59);">.</span>require_timeout<span style="color: rgb(43, 48, 59);">(</span><span style="color: rgb(0, 128, 128);">3.0</span><span style="color: rgb(43, 48, 59);">)</span>
</span><span>
</span><span><span style="color: rgb(110, 118, 135);"># Use:</span>
</span><span>require_timeout = <span style="color: rgb(0, 81, 194);">getattr</span><span style="color: rgb(43, 48, 59);">(</span>unit<span style="color: rgb(43, 48, 59);">,</span> <span style="color: rgb(0, 128, 0);">"require_timeout"</span><span style="color: rgb(43, 48, 59);">,</span> <span style="color: rgb(0, 128, 128);">None</span><span style="color: rgb(43, 48, 59);">)</span>
</span><span><span style="color: rgb(129, 0, 194);">if</span> require_timeout <span style="color: rgb(129, 0, 194);">is</span> <span style="color: rgb(129, 0, 194);">not</span> <span style="color: rgb(0, 128, 128);">None</span><span style="color: rgb(43, 48, 59);">:</span>
</span><span>    require_timeout<span style="color: rgb(43, 48, 59);">(</span>VARTA_TIMEOUT<span style="color: rgb(43, 48, 59);">)</span></span></span></code></pre></div></div></div>
<p dir="ltr">Same pattern applies to <code>require_message_spacing</code> and <code>require_connect_delay</code>.</p>
<p dir="ltr"><strong>Versions summary</strong></p>
<div dir="ltr">
Version | HA 2026.9 compatible
-- | --
1.1.2 | ❌ AttributeError on TmodbusUnit
1.1.1 | ✅ Works
1.1.0 | unknown
1.0.0 | unknown

</div>

</body>
</html>
